# Generated by Django 5.2 on 2025-08-20 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=200)),
                ('email_host_password', models.CharField(max_length=200)),
                ('bot_token', models.CharField(max_length=200)),
                ('channel_username', models.CharField(max_length=200)),
                ('manager', models.URLField(default='https://t.me/telegram')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
