# Generated by Django 5.2 on 2025-08-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
