# Generated by Django 5.2 on 2025-08-08 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercarimport',
            options={'verbose_name': 'Порядок покупки и доставки автомобиля из Кореи', 'verbose_name_plural': 'Порядок покупки и доставки автомобиля из Кореи'},
        ),
        migrations.AlterModelOptions(
            name='securetransaction',
            options={'verbose_name': 'Безопасная сделка', 'verbose_name_plural': 'Безопасная сделка'},
        ),
    ]
