# Generated by Django 5.2 on 2025-08-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='brand/icons/'),
        ),
    ]
