# Generated by Django 5.2 on 2025-08-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='main_image',
            field=models.ImageField(null=True, upload_to='car/images/'),
        ),
    ]
