# Generated by Django 5.2 on 2025-08-02 11:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_brand_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.PositiveBigIntegerField()),
                ('date', models.DateField()),
                ('engine_capacity', models.PositiveIntegerField()),
                ('miliage', models.PositiveBigIntegerField()),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.bodytype')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.brand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.color')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.fueltype')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.generation')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.model')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.transmission')),
            ],
            options={
                'verbose_name': 'автомобил',
                'verbose_name_plural': 'автомобили',
            },
        ),
    ]
