# Generated by Django 5.2 on 2025-08-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='date',
        ),
        migrations.AddField(
            model_name='car',
            name='month',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
