# Generated by Django 5.2 on 2025-08-02 12:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ImageField(upload_to='car/media/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_medias', to='cars.car')),
            ],
            options={
                'verbose_name': 'изображение автомобиля',
                'verbose_name_plural': 'изображения автомобилей',
            },
        ),
    ]
