# Generated by Django 5.2 on 2025-08-02 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_carmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInteryer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_airbag', models.BooleanField(default=False, verbose_name='Боковая подушка безопасности')),
                ('curtain_airbag', models.BooleanField(default=False, verbose_name='Шторка безопасности')),
                ('abs', models.BooleanField(default=False, verbose_name='Система антиблокировки тормозов (ABS)')),
                ('traction_control', models.BooleanField(default=False, verbose_name='Система контроля тяги (TCS)')),
                ('esc', models.BooleanField(default=False, verbose_name='Система электронной стабилизации (ESC)')),
                ('tpms', models.BooleanField(default=False, verbose_name='Система контроля давления в шинах (TPMS)')),
                ('ldws', models.BooleanField(default=False, verbose_name='Система предупреждения о выходе из полосы (LDWS)')),
                ('rear_view_camera', models.BooleanField(default=False, verbose_name='Камера заднего вида')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_interyer', to='cars.car')),
            ],
            options={
                'verbose_name': 'Экстерьер/Интерьер',
                'verbose_name_plural': 'Экстерьер/Интерьер',
            },
        ),
        migrations.CreateModel(
            name='CarMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cruise_control', models.BooleanField(default=False, verbose_name='Круиз-контроль (обычный/адаптивный)')),
                ('leather_seats', models.BooleanField(default=False, verbose_name='Кожаные сиденья')),
                ('seat_electric_adjustment_front', models.BooleanField(default=False, verbose_name='Электрорегулировка сидений (водитель/пассажир)')),
                ('seat_electric_adjustment_rear', models.BooleanField(default=False, verbose_name='Электрорегулировка сидений (задний ряд)')),
                ('seat_heating_front_rear', models.BooleanField(default=False, verbose_name='Подогрев сидений (передних/задних)')),
                ('seat_memory_front', models.BooleanField(default=False, verbose_name='Память сидений (водитель/пассажир)')),
                ('seat_ventilation_front', models.BooleanField(default=False, verbose_name='Вентилируемые сиденья (водитель/пассажир)')),
                ('seat_ventilation_rear', models.BooleanField(default=False, verbose_name='Вентилируемые сиденья (задний ряд)')),
                ('massage_seats', models.BooleanField(default=False, verbose_name='Массажные сиденья')),
                ('abs_system', models.BooleanField(default=False, verbose_name='Система антиблокировки тормозов (ABS)')),
                ('rear_av_monitor', models.BooleanField(default=False, verbose_name='AV-монитор задних сидений')),
                ('cd_player', models.BooleanField(default=False, verbose_name='CD-плеер')),
                ('usb_port', models.BooleanField(default=False, verbose_name='USB-порт')),
                ('aux_port', models.BooleanField(default=False, verbose_name='AUX-порт')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_multimedia', to='cars.car')),
            ],
            options={
                'verbose_name': 'Удобство / Мультимедиа',
                'verbose_name_plural': 'Удобство / Мультимедиа',
            },
        ),
        migrations.CreateModel(
            name='CarSafety',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('epb', models.BooleanField(default=False, verbose_name='Электронный стояночный тормоз (EPB)')),
                ('automatic_ac', models.BooleanField(default=False, verbose_name='Автоматический кондиционер')),
                ('smart_key', models.BooleanField(default=False, verbose_name='Умный ключ')),
                ('wireless_door_lock', models.BooleanField(default=False, verbose_name='Беспроводной замок двери')),
                ('rain_sensor', models.BooleanField(default=False, verbose_name='Датчик дождя')),
                ('auto_light', models.BooleanField(default=False, verbose_name='Автоматический свет')),
                ('navigation', models.BooleanField(default=False, verbose_name='Навигация')),
                ('bluetooth', models.BooleanField(default=False, verbose_name='Bluetooth')),
                ('usb_port', models.BooleanField(default=False, verbose_name='USB-порт')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_safety', to='cars.car')),
            ],
            options={
                'verbose_name': 'Безопасность',
                'verbose_name_plural': 'Безопасность',
            },
        ),
        migrations.CreateModel(
            name='CarSeats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seat_leather', models.BooleanField(default=False, verbose_name='Кожаные сиденья')),
                ('seat_electric_adjustment_driver_passenger', models.BooleanField(default=False, verbose_name='Электрорегулировка сидений (водитель/пассажир)')),
                ('seat_electric_adjustment_rear_seats', models.BooleanField(default=False, verbose_name='Электрорегулировка сидений (задний ряд)')),
                ('seat_heating_all', models.BooleanField(default=False, verbose_name='Подогрев сидений (передних/задних)')),
                ('seat_memory_all', models.BooleanField(default=False, verbose_name='Память сидений (водитель/пассажир)')),
                ('seat_ventilation_driver_passenger', models.BooleanField(default=False, verbose_name='Вентилируемые сиденья (водитель/пассажир)')),
                ('seat_ventilation_back', models.BooleanField(default=False, verbose_name='Вентилируемые сиденья (задний ряд)')),
                ('seat_massage', models.BooleanField(default=False, verbose_name='Массажные сиденья')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_seats', to='cars.car')),
            ],
            options={
                'verbose_name': 'Сиденья',
                'verbose_name_plural': 'Сиденья',
            },
        ),
    ]
