# Generated by Django 5.2 on 2025-08-03 08:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_like_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_service', models.PositiveBigIntegerField(verbose_name='Услуги агента')),
                ('car_cost', models.PositiveBigIntegerField(verbose_name='Стоимость авто')),
                ('expences_in_korea', models.PositiveBigIntegerField(verbose_name='расходы в Корее')),
                ('custom_dutie', models.PositiveBigIntegerField(verbose_name='Таможенные платежи')),
                ('utilsbor', models.PositiveBigIntegerField(verbose_name='Утильсбор')),
                ('custom_broker', models.PositiveBigIntegerField(verbose_name='Таможенный брокер')),
                ('car_transporter', models.PositiveBigIntegerField(verbose_name='Автовоз')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_pricing', to='cars.car')),
            ],
            options={
                'verbose_name': 'расчет цены',
                'verbose_name_plural': 'расчет цены',
            },
        ),
    ]
