# Generated by Django 5.2 on 2025-08-03 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_carpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата инспекции')),
                ('diagnosis_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата диагностики')),
                ('vin', models.CharField(blank=True, max_length=100, null=True, verbose_name='VIN')),
                ('engine_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип мотора')),
                ('incidents', models.CharField(blank=True, max_length=255, null=True, verbose_name='Инциденты')),
                ('year', models.CharField(blank=True, max_length=10, null=True, verbose_name='Год модели')),
                ('usage_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип использования')),
                ('front_left_door', models.CharField(blank=True, max_length=50, null=True, verbose_name='Передняя левая дверь')),
                ('front_right_door', models.CharField(blank=True, max_length=50, null=True, verbose_name='Передняя правая дверь')),
                ('rear_left_door', models.CharField(blank=True, max_length=50, null=True, verbose_name='Задняя левая дверь')),
                ('rear_right_door', models.CharField(blank=True, max_length=50, null=True, verbose_name='Задняя правая дверь')),
                ('hood', models.CharField(blank=True, max_length=50, null=True, verbose_name='Капот')),
                ('trunk', models.CharField(blank=True, max_length=50, null=True, verbose_name='Крышка багажника')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_inspections', to='cars.car')),
            ],
            options={
                'verbose_name': 'Проверка авто',
                'verbose_name_plural': 'Проверка авто',
            },
        ),
        migrations.CreateModel(
            name='CarInspectionIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_incidents', to='cars.carinspection')),
            ],
            options={
                'verbose_name': 'Страховые случаи',
                'verbose_name_plural': 'Страховые случаи',
            },
        ),
        migrations.CreateModel(
            name='InspectionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cars.carinspection')),
            ],
            options={
                'verbose_name': 'Внутренняя инспекция',
                'verbose_name_plural': 'Внутренняя инспекция',
            },
        ),
        migrations.CreateModel(
            name='InspectionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='cars.inspectionsection')),
            ],
            options={
                'verbose_name': 'Внутренняя инспекция',
                'verbose_name_plural': 'Внутренняя инспекция',
            },
        ),
    ]
