# Generated by Django 5.2 on 2025-08-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
    ]
